[build]
  command = "pnpm install --recursive && pnpm --filter=root run build && pnpm --filter=axiom-playground run generate"
  publish = "playground/.output/public"

[build.environment]
  NODE_VERSION = "20"
